version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Verify.Xunit
    versions:
    - 10.7.0
    - 10.8.0
    - 10.9.0
    - 11.0.3
    - 11.1.0
  - dependency-name: MarkdownSnippets.MsBuild
    versions:
    - 23.1.1
