image: Visual Studio 2017
services:
- mssql2017
build_script:
- ps: >-
    dotnet build src --configuration Release

    dotnet test src --configuration Release --no-build --no-restore
artifacts:
- path: nugets\**\*.nupkg